[project]
name = "ccwc-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Scott Powers", email = "spowers.42@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "typer>=0.27.1",
]

[project.scripts]
ccwc-py = "ccwc_py:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
